version: '3.8'

services:
  mysql:
    image: mysql:8.0.35
    container_name: bank-api-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bank_api
      MYSQL_USER: bank_user
      MYSQL_PASSWORD: bank_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
    networks:
      - bank-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: bank-api-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "8180:8080"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/realm.json
    command: start-dev --import-realm
    networks:
      - bank-network

  adminer:
    image: adminer
    container_name: bank-api-adminer
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - bank-network

volumes:
  mysql_data:

networks:
  bank-network:
    driver: bridge